name: flutter_tic_tac_toe
version: 1.0.0+2
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=3.1.2 <4.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.6
  flutter: 
    sdk: flutter
  isar: ^3.1.0+1
  isar_flutter_libs:
    git:
      url: https://github.com/MrLittleWhite/isar_flutter_libs.git
  path_provider: ^2.1.1
  google_fonts: ^6.1.0
  sign_in_button: ^3.2.0
  flutter_svg: ^2.0.9
  firebase_auth: ^4.14.1
  firebase_core: ^2.23.0
  google_sign_in: ^6.1.6
  cached_network_image: ^3.3.0
  flutter_cache_manager: ^3.3.1
  cloud_firestore: ^4.13.5
  app_state: ^0.9.4
  http: ^1.1.2
  json_annotation: ^4.8.1
  uuid: ^4.2.2
  logger: ^2.0.2+1
  font_awesome_flutter: ^10.6.0
  gap: ^3.0.1
  mocktail: ^1.0.2
  flutter_launcher_icons: ^0.14.3


dev_dependencies: 
  build_runner: ^2.4.6
  flutter_lints: 2.0.3
  flutter_test: 
    sdk: flutter
  integration_test:
    sdk: flutter
  isar_generator: ^3.1.0+1
  json_serializable: ^6.7.1

flutter_icons:
  android: true
  ios: true
  image_path: "assets/logo.jpg"
  adaptive_icon_foreground: "assets/logo_foreground.png"
  adaptive_icon_background: "#ffffff"

flutter: 
  uses-material-design: true
  assets:
    - assets/images/
  fonts:
    - family: Jomhuria     
      fonts:
        - asset: assets/fonts/Jomhuria-Regular.ttf

